services:
  - type: web
    name: lms-server
    env: node
    region: oregon # or singapore for closer to your users
    plan: starter # or standard/pro based on your needs
    buildCommand: npm run render:build
    startCommand: npm run render:start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lms-db
          property: connectionString
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_WEBHOOK_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://your-client-app.onrender.com

databases:
  - name: lms-db
    databaseName: lms_production
    user: lms_user
    region: oregon # should match your web service region
    plan: starter # or standard/pro based on your needs
